### ISSUE TITLE
issues with chumpy is there a workaround?

### ISSUE THREAD

**Issue by Hermeskid123** [lixiny/manotorch#12]
when I try to run pip install. 

Processing /home/preston/Git/manotorch
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/preston/Git/manotorch/setup.py", line 36, in <module>
          check_dependencies()
        File "/home/preston/Git/manotorch/setup.py", line 23, in check_dependencies
          __import__(package_name)
        File "/home/preston/miniconda3/envs/manotorch/lib/python3.11/site-packages/chumpy/__init__.py", line 1, in <module>
          from .ch import *
        File "/home/preston/miniconda3/envs/manotorch/lib/python3.11/site-packages/chumpy/ch.py", line 1319, in <module>
          from . import linalg
        File "/home/preston/miniconda3/envs/manotorch/lib/python3.11/site-packages/chumpy/linalg.py", line 178, in <module>
          class SvdD(Ch):
        File "/home/preston/miniconda3/envs/manotorch/lib/python3.11/site-packages/chumpy/linalg.py", line 181, in SvdD
          @depends_on('x')
           ^^^^^^^^^^^^^^^
        File "/home/preston/miniconda3/envs/manotorch/lib/python3.11/site-packages/chumpy/ch.py", line 1203, in _depends_on
          want_out = 'out' in inspect.getargspec(func).args
                              ^^^^^^^^^^^^^^^^^^
      AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by cappelletto** [comment]
The issue persists even after installing chumpy (0.7.1) from the git repo. Some suggest that one way to circumvent this is using older Python versions (<3.6)
```

    want_out = 'out' in inspect.getargspec(func).args
                        ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

```

**Comment by lianghongzhuo** [comment]
use the current open pr in chumpy:
https://github.com/mattloper/chumpy/pull/59
pip install git+https://github.com/uyoung-jeong/chumpy.git
and give a thumbs up to make merge faster.

**Comment by Hermeskid123** [comment]
pip install git+https://github.com/mattloper/chumpy@9b045ff5d6588a24a0bab52c83f032e2ba433e17 also works
